#!/usr/bin/env bash
# One-time install on a fresh Ubuntu 22.04 / 24.04 server (run as root or with sudo):
#   sudo bash install.sh
# Installs Docker and a firewall, writes deploy/.env with new random secrets, starts everything, creates the
# first accounts, and schedules the nightly backup. Safe to re-run: an existing .env is kept.
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v docker >/dev/null 2>&1; then
  echo ">> Installing Docker"
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg ufw
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
fi

echo ">> Firewall: only SSH, HTTP and HTTPS"
ufw allow OpenSSH >/dev/null; ufw allow 80/tcp >/dev/null; ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null

if [ ! -f .env ]; then
  read -rp "Domain for the web portals (e.g. app.jibaya.iq): " APP_DOMAIN
  read -rp "Domain for the API (e.g. api.jibaya.iq): " API_DOMAIN
  read -rp "Company WhatsApp number citizens message (9647XXXXXXXXX): " WA_NUMBER
  rnd() { openssl rand -hex 32; }
  SEED_PASSWORD="Jb-$(openssl rand -base64 12 | tr -dc 'A-Za-z0-9' | head -c 12)"
  cat > .env <<ENV
# ---- generated by install.sh on $(date -u +%F). Keep this file secret and backed up. ----
APP_DOMAIN=$APP_DOMAIN
API_DOMAIN=$API_DOMAIN
POSTGRES_PASSWORD=$(rnd)
JWT_SECRET=$(rnd)
OTP_SECRET=$(rnd)
MASTER_CODE_SECRET=$(rnd)
SEED_PASSWORD=$SEED_PASSWORD
CORS_ORIGIN_REGEX=https://${APP_DOMAIN//./\\.}
APP_TIMEZONE=Asia/Baghdad
DEVICE_APPROVAL_REQUIRED=true
# WhatsApp: stays in test mode (console) until you fill these and set WHATSAPP_MODE=live (see README.md)
WHATSAPP_MODE=console
WHATSAPP_BUSINESS_NUMBER=$WA_NUMBER
WHATSAPP_TOKEN=
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_APP_SECRET=
WHATSAPP_VERIFY_TOKEN=$(openssl rand -hex 16)
# the 35% rule stays "not set" until the contract wording is confirmed
GAIN_SHARE_MODE=not_set
# only if the server has no public IP (see README.md)
CLOUDFLARE_TUNNEL_TOKEN=
ENV
  chmod 600 .env
  echo ">> Wrote deploy/.env"
fi

mkdir -p web backups
if [ ! -f web/index.html ]; then
  echo "<!doctype html><meta charset=utf-8><p>ارفع نسخة الويب (flutter build web) إلى deploy/web</p>" > web/index.html
fi

echo ">> Starting the system"
docker compose up -d --build
echo ">> Waiting for the API"
for i in $(seq 1 60); do
  if docker compose exec -T api python -c "import urllib.request;urllib.request.urlopen('http://127.0.0.1:8000/health')" 2>/dev/null; then break; fi
  sleep 2
done

echo ">> Creating the first accounts (only adds what is missing)"
docker compose exec -T api python -m app.seed

echo ">> Nightly backup at 02:30"
CRON="30 2 * * * root bash $(pwd)/backup.sh >> $(pwd)/backups/backup.log 2>&1"
echo "$CRON" > /etc/cron.d/jibaya-backup

echo
echo "Done."
echo " - Web portals:  https://$(grep ^APP_DOMAIN .env | cut -d= -f2)"
echo " - API:          https://$(grep ^API_DOMAIN .env | cut -d= -f2)/health"
echo " - First accounts' password is SEED_PASSWORD in deploy/.env. Log into TECH-01 FIRST, then change every password."
